env:
  global:
    - secure: qhTaj6f9EyIrkQOhYISC4hbEyvpYC8w+AInwSd1ftWb45K3k+ZfGMZ5sIf1FXEc9cOBO/xQWLjbTpT48tB/DtVnAhEYOPnPhrfta/gTHlJsweWc61s7xBonMFi8vVr7l6eFefAX5F5UHm6CGQOm3QZcQgtr3gricKG/PhF7u0sVe6WGwIMvCmrGzHAhT1lSb+l4IYWpieuSijDP5fOetDKXhpLYuDlkx+8sPKHQQ1p8g5a0U7bhMQm2NdYzZlHE35T3EkL02Q+nqXmGeXnWWTQLEOjYXebYZN94VNuRwawy7xEjphtzYyomMwtlmQ083UmaZseIG0gUbpC9tKk/w5O46PlBgixCWS6OiSs+s00S+q69LN/DFPQrXwnpAck6X+5dw/z2iXNefr6n5JcUotQyzjpdpSZSa1z9qImE9KqEyzKrEkFRvoC6rnfJWhjo4/2TsRuPN+vrPkOwEtJEbg7vtr3wERxxFsnbWNBsnbtGe1z/t2GhQL97n0t4Yzp+WxcJZv/PbCX+X57BkCZlXNbuUzo+8bloBBItIJcw8CqJ+b18V5KN4tmTBsMkL+c+aD2Oi/banr3ilhG7qEGufOfJ4i7hIay6vxNxG0tdWEdb1O7eZPKiAQtWnSBJv2/DYZmLibWU+p+S0C2ketL122vE0zWrT3IiXF8zCGSNHSsI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts-list_web_malwaredomainlist.com
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

before_script:
  - if [[ ! -f .administrators ]]; then wget "${UPDATE_ME_LOCATION}" -o /dev/null -O update_me.py && chmod +x update_me.py; else echo "update_me not downloaded :)"; fi
  - if [[ ! -f .administrators ]]; then wget "${ADMIN_LOCATION}" -o /dev/null -O admin.py && chmod +x admin.py; else echo "admin not downloaded :)"; fi

script:
  - python3 update_me.py

notifications:
  on_success: change
  on_failure: always
