env:
  global:
    - secure: iF5dkrRx6/0Vje3Ox1aJtlXxh0zBfdzCjBYh3nJCNWt0xF3RJqwHHepFFbsyGGI+zmhlFukOl2JEw7ag8BmkpxpYOaCUThnQuCA0HnjDUKIia5eqP7utOda5XAuEfyla3GMzw7tPxlLgpdVMHxDKuyb66KDEA0VAcQiqZhR0MuILGFMgqIFgR3A9cIP1zVFu3potefYtcjIYg7yoEg6+5yGk4VLijoBy4cGVsm2n1WkP+4qR3vWQNnm96djSeRAQ7Zsc7netdBiSV3Qn4XQTacUYGNwdeO8eNmnK3BC5KeAWT2LmRepkqv+lPgewHzBfW/qkx2r/63rLi9n2cYYgwg3XBfohrwYrnJxZHp+Z5KBLvPktU8KSJmF6XPdnD5+e+Vm0tlR0eQsAYb8a8uoLvhQeUHAg4t7AJHaOzttLLhMEtAg8ApQgAo3OH3n4q2CapfQLTDA6XEFkwmQ7sUlgcWuetl8VJTg+M3dEyliLZNvYX3+dc01M2oCeBbhGv6vH1pNrHjHp2TmbCI4oIeKLxdMLZDJgx/yMYOIXt8U1whbnNZdp9AhlOZlGWcQuulQMwed/Ypvo0cu+eECTkMGpvdPxoC29mUICZf0kBJd6cMiQHLtPHRT/lNJYMZUMv3DMkRpsYi9AHi9uPurcKAogJ89az/USFXvv4nhEFXz/8hA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts-list_web_malwaredomainlist.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
