env:
  global:
    - secure: iWTyxWORD4WwG0nDUb9GR0r8DTUwC6la3C5SgAVTI35Kr30tmk761FnobE9w6RbpHevQLNYBvZWU84SMHunb7adW/VzELUVi54ZUQq4sIOR9DMVMVf4xwsSdcAI4x/8goZ/nzMV1O1Lt/SHKxw+XhivNJWtxgA8bNRQ9CXDtLHs56ogGT5tCDxQZUlsSyVMBu7uiF9hYx5ooHIa2TxSjVRn6Q7/izguUfhgAUUAuKnY5y+Jar7hM8YWiFmg8d2A0KxoGLD+KS0DckOg8Itw4QzRaKRasJn/9hd4oF606r8iv33oLSpUlIPnskGbBXmeP5g+a/GGi0Mu2iSuMHCRz0vwiQzGikaws7zz3fnzjr4P1hdeyUXZLlc49tE/Asr3WuKEszFXuHc+i4L7GUsuv4+gpTioNVwszYaXpmU59u+L+CPii4pcJKadKv9kO4hbpaouiHsW6iXuFYB412YBAZIx9YYzihzgFLlJEDAM+4DoDVEX+mY4XnxgwwZwp6JrZSX6qfkZ3/3ffwacojw6hwZw9rLW42sz1QqvI53s/8NBdtd0uem9ozNY5gMgxlPyEEbwUOcy7cNYPJmuyf553Y48K2e5VNDkhjzUwmsp4x6e5SN2lHQC4b9rITvqKUdP/NmL5Fa3k6FRoanldGzunGi5fjJjYSSIljZvMJ/Gf8uU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts-list_web_malwaredomainlist.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
