dist: bionic
env:
    global:
    -   secure: WFWAQhnw0wVOdnOGSdmLURqwNC7GzBCIOdiLBaS/cy50AxLEcwebm4IShl4J2VwDFqd3zbGDSZJFM6O2Wc2AqYA4NvSt/cs3qZh98yCicrHn1DEC1TbhRFubD2hdFMJd6+Fcv3geWMigytugglJLhNVwjF8cA/SVgc+OsQf+/5h/4mqRgqzbwJYLAskq82YIXIjCYTD7WNQd6jYpy55rL15u/JFvzxB+ObNovPWlkgaab3+XUFhGPe85buZCJI2oqTh6gZkMv8HmnMFdXeWT4ey20IQBg2vQycsMjK5iZXRXKWryj/+jwC+Flvy0VE6icMC02NfZRNBm6mfxUuvzngK3qcgI5ioKuQVE+VToMuZ8iUZvkKCAIk4hlKNKtyssw/ZCYK5MdOyrA80mcGNmqN5z+4blDuQqC0NLUSLpXicLFMHgqlmBsOlqgXEbtVKi64yPza5GiyZAqM2oCkNlEwy96z9giMkPuIIaQe0wyZ0No0E14XY0w8EPFBpb/5EBGvPy7uxSJIGnEthrnJZc56tKoyoNa3lB4+dQzG3SiWH9R57e/TIMGLlxUJjcSoVUbwrx+W1bL+jBefaSRChf7Y7KPjV+meu1GUTN1XsL2RkmhmOPFIOoTDUgMILnNyMGqpoIwdHf/UO1OzlvGDjwUjxC+dB/QqKc93oZaJvWLbs=
    -   GIT_NAME: Dead-Hosts
    -   GIT_EMAIL: dead-hosts@outlook.com
    -   GIT_BRANCH: master
    -   PYTHON_VERSION: 3.7.5
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n launcher-environment python="${PYTHON_VERSION}"
- conda activate launcher-environment
- python -VV
- pip --version
- pip install --upgrade dead-hosts-launcher
- rm miniconda.sh
language: generic
notifications:
    email:
        on_failure: always
        on_success: change
        recipients:
        - dead-hosts@outlook.com
os:
- linux
script:
- dead_hosts_launcher --version
- dead_hosts_launcher
