env:
  global:
    - secure: AU6d174aQVkysZgz1Gs8KxsOaqnYxHy+79c0VdBSM6H0ud9sl2ro58yJ9EGQuR8b6KOH6/pY3q2inCjgqx1V+ow2TzzF4jA8BXH7DcIhqgHAiAKfIj48LVdUMO312iWqS7HYqm86ue2J9RQ64bBlX1Af6SSVw/FxTopg6Qol4tC4lnS6qmwoJc1EHJpW6eP/occJfXLgk5prpEBzZKPPQyt3cez3i3LSnxKoOV3xkyWzFcoJ/fKGkmqwQj8HDjvC0R1onX+vLyyl6ulF6pw9qo9+32z3fJlsA07IbkqrMoPMQ/i0Xb9jtQTFGaFRAqZyorgbsoRXprR4kdTxUTp5fompDvgHaOknSX4xHMutw6C95quVYKk7Og5Ac9whLoYdN+keNQGJWKbpQ4dMfqRv9p7D41An+7A0of9m/jodIfNyhQ16T41QnGrxzTM4VwFx7RGB03sIYTaq5sGa4iUTWzfgLT7H5MOdj5DcCt3epvP5GhD14ytfJ6bjXgZ2miSxz5Atqm1WQeDPb792jw7ZVCjcHILsDg1d+HxXGktEKrN/iSPyC08fvTp7eozB0ZQH/VsWY3UZ80DM0tc3kZ+vDCIMMZCTbwU9dNkIyYcuyZ1c+YiCTPWEBjROiBvuffc/pXA7EVPzYhoWU69oqqJ/BI78j4gorOrb7Oq6rcbhwWc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts-list_web_malwaredomainlist.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
